name = "SciMLMiniCourse"
uuid = "e142e7c2-b473-410e-9fa9-8ea67e1e704d"
authors = ["Stephan Scholz"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
